# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ReferralPayoutAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'ReferralCurrency',
        'payout_address': 'str'
    }

    attribute_map = {
        'currency': 'currency',
        'payout_address': 'payout_address'
    }

    def __init__(self, currency=None, payout_address=None, _configuration=None):  # noqa: E501
        """ReferralPayoutAddress - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._currency = None
        self._payout_address = None
        self.discriminator = None

        self.currency = currency
        self.payout_address = payout_address

    @property
    def currency(self):
        """Gets the currency of this ReferralPayoutAddress.  # noqa: E501


        :return: The currency of this ReferralPayoutAddress.  # noqa: E501
        :rtype: ReferralCurrency
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this ReferralPayoutAddress.


        :param currency: The currency of this ReferralPayoutAddress.  # noqa: E501
        :type: ReferralCurrency
        """
        if self._configuration.client_side_validation and currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency

    @property
    def payout_address(self):
        """Gets the payout_address of this ReferralPayoutAddress.  # noqa: E501


        :return: The payout_address of this ReferralPayoutAddress.  # noqa: E501
        :rtype: str
        """
        return self._payout_address

    @payout_address.setter
    def payout_address(self, payout_address):
        """Sets the payout_address of this ReferralPayoutAddress.


        :param payout_address: The payout_address of this ReferralPayoutAddress.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and payout_address is None:
            raise ValueError("Invalid value for `payout_address`, must not be `None`")  # noqa: E501

        self._payout_address = payout_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReferralPayoutAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReferralPayoutAddress):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReferralPayoutAddress):
            return True

        return self.to_dict() != other.to_dict()
