# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ContainerFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'description': 'str',
        'rows': 'int',
        'cols': 'int'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'description': 'description',
        'rows': 'rows',
        'cols': 'cols'
    }

    def __init__(self, name=None, type=None, description=None, rows=None, cols=None, _configuration=None):  # noqa: E501
        """ContainerFields - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._type = None
        self._description = None
        self._rows = None
        self._cols = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if description is not None:
            self.description = description
        if rows is not None:
            self.rows = rows
        if cols is not None:
            self.cols = cols

    @property
    def name(self):
        """Gets the name of this ContainerFields.  # noqa: E501

        Container name  # noqa: E501

        :return: The name of this ContainerFields.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ContainerFields.

        Container name  # noqa: E501

        :param name: The name of this ContainerFields.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this ContainerFields.  # noqa: E501

        used to dispaly shape  # noqa: E501

        :return: The type of this ContainerFields.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ContainerFields.

        used to dispaly shape  # noqa: E501

        :param type: The type of this ContainerFields.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def description(self):
        """Gets the description of this ContainerFields.  # noqa: E501


        :return: The description of this ContainerFields.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ContainerFields.


        :param description: The description of this ContainerFields.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def rows(self):
        """Gets the rows of this ContainerFields.  # noqa: E501

        Amount of rows in the container  # noqa: E501

        :return: The rows of this ContainerFields.  # noqa: E501
        :rtype: int
        """
        return self._rows

    @rows.setter
    def rows(self, rows):
        """Sets the rows of this ContainerFields.

        Amount of rows in the container  # noqa: E501

        :param rows: The rows of this ContainerFields.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                rows is not None and rows < 1):  # noqa: E501
            raise ValueError("Invalid value for `rows`, must be a value greater than or equal to `1`")  # noqa: E501

        self._rows = rows

    @property
    def cols(self):
        """Gets the cols of this ContainerFields.  # noqa: E501

        Amount of rows in the container  # noqa: E501

        :return: The cols of this ContainerFields.  # noqa: E501
        :rtype: int
        """
        return self._cols

    @cols.setter
    def cols(self, cols):
        """Sets the cols of this ContainerFields.

        Amount of rows in the container  # noqa: E501

        :param cols: The cols of this ContainerFields.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                cols is not None and cols < 1):  # noqa: E501
            raise ValueError("Invalid value for `cols`, must be a value greater than or equal to `1`")  # noqa: E501

        self._cols = cols

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContainerFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerFields):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContainerFields):
            return True

        return self.to_dict() != other.to_dict()
