# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class FarmPersonalSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_favorite': 'bool',
        'note': 'str'
    }

    attribute_map = {
        'is_favorite': 'is_favorite',
        'note': 'note'
    }

    def __init__(self, is_favorite=None, note=None, _configuration=None):  # noqa: E501
        """FarmPersonalSettings - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_favorite = None
        self._note = None
        self.discriminator = None

        if is_favorite is not None:
            self.is_favorite = is_favorite
        if note is not None:
            self.note = note

    @property
    def is_favorite(self):
        """Gets the is_favorite of this FarmPersonalSettings.  # noqa: E501

        Is favorite flag  # noqa: E501

        :return: The is_favorite of this FarmPersonalSettings.  # noqa: E501
        :rtype: bool
        """
        return self._is_favorite

    @is_favorite.setter
    def is_favorite(self, is_favorite):
        """Sets the is_favorite of this FarmPersonalSettings.

        Is favorite flag  # noqa: E501

        :param is_favorite: The is_favorite of this FarmPersonalSettings.  # noqa: E501
        :type: bool
        """

        self._is_favorite = is_favorite

    @property
    def note(self):
        """Gets the note of this FarmPersonalSettings.  # noqa: E501

        Personal note for the farm  # noqa: E501

        :return: The note of this FarmPersonalSettings.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this FarmPersonalSettings.

        Personal note for the farm  # noqa: E501

        :param note: The note of this FarmPersonalSettings.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                note is not None and len(note) > 1000):
            raise ValueError("Invalid value for `note`, length must be less than or equal to `1000`")  # noqa: E501

        self._note = note

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FarmPersonalSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FarmPersonalSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FarmPersonalSettings):
            return True

        return self.to_dict() != other.to_dict()
