# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class FarmHashrates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hashrates': 'list[object]',
        'hashrates_by_coin': 'list[object]'
    }

    attribute_map = {
        'hashrates': 'hashrates',
        'hashrates_by_coin': 'hashrates_by_coin'
    }

    def __init__(self, hashrates=None, hashrates_by_coin=None, _configuration=None):  # noqa: E501
        """FarmHashrates - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hashrates = None
        self._hashrates_by_coin = None
        self.discriminator = None

        if hashrates is not None:
            self.hashrates = hashrates
        if hashrates_by_coin is not None:
            self.hashrates_by_coin = hashrates_by_coin

    @property
    def hashrates(self):
        """Gets the hashrates of this FarmHashrates.  # noqa: E501


        :return: The hashrates of this FarmHashrates.  # noqa: E501
        :rtype: list[object]
        """
        return self._hashrates

    @hashrates.setter
    def hashrates(self, hashrates):
        """Sets the hashrates of this FarmHashrates.


        :param hashrates: The hashrates of this FarmHashrates.  # noqa: E501
        :type: list[object]
        """

        self._hashrates = hashrates

    @property
    def hashrates_by_coin(self):
        """Gets the hashrates_by_coin of this FarmHashrates.  # noqa: E501

        Summary hashrates per coin  # noqa: E501

        :return: The hashrates_by_coin of this FarmHashrates.  # noqa: E501
        :rtype: list[object]
        """
        return self._hashrates_by_coin

    @hashrates_by_coin.setter
    def hashrates_by_coin(self, hashrates_by_coin):
        """Sets the hashrates_by_coin of this FarmHashrates.

        Summary hashrates per coin  # noqa: E501

        :param hashrates_by_coin: The hashrates_by_coin of this FarmHashrates.  # noqa: E501
        :type: list[object]
        """

        self._hashrates_by_coin = hashrates_by_coin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FarmHashrates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FarmHashrates):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FarmHashrates):
            return True

        return self.to_dict() != other.to_dict()
