# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class FarmAutocreateHash(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'autocreate_hash': 'str'
    }

    attribute_map = {
        'autocreate_hash': 'autocreate_hash'
    }

    def __init__(self, autocreate_hash=None, _configuration=None):  # noqa: E501
        """FarmAutocreateHash - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._autocreate_hash = None
        self.discriminator = None

        if autocreate_hash is not None:
            self.autocreate_hash = autocreate_hash

    @property
    def autocreate_hash(self):
        """Gets the autocreate_hash of this FarmAutocreateHash.  # noqa: E501

        Unique ID to be used for connecting new workers to the farm  # noqa: E501

        :return: The autocreate_hash of this FarmAutocreateHash.  # noqa: E501
        :rtype: str
        """
        return self._autocreate_hash

    @autocreate_hash.setter
    def autocreate_hash(self, autocreate_hash):
        """Sets the autocreate_hash of this FarmAutocreateHash.

        Unique ID to be used for connecting new workers to the farm  # noqa: E501

        :param autocreate_hash: The autocreate_hash of this FarmAutocreateHash.  # noqa: E501
        :type: str
        """

        self._autocreate_hash = autocreate_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FarmAutocreateHash, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FarmAutocreateHash):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FarmAutocreateHash):
            return True

        return self.to_dict() != other.to_dict()
