# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class GpuFlashedRom(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rom_id': 'int',
        'rom_name': 'str',
        'time': 'int'
    }

    attribute_map = {
        'rom_id': 'rom_id',
        'rom_name': 'rom_name',
        'time': 'time'
    }

    def __init__(self, rom_id=None, rom_name=None, time=None, _configuration=None):  # noqa: E501
        """GpuFlashedRom - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._rom_id = None
        self._rom_name = None
        self._time = None
        self.discriminator = None

        if rom_id is not None:
            self.rom_id = rom_id
        if rom_name is not None:
            self.rom_name = rom_name
        if time is not None:
            self.time = time

    @property
    def rom_id(self):
        """Gets the rom_id of this GpuFlashedRom.  # noqa: E501

        Rom ID that was flashed  # noqa: E501

        :return: The rom_id of this GpuFlashedRom.  # noqa: E501
        :rtype: int
        """
        return self._rom_id

    @rom_id.setter
    def rom_id(self, rom_id):
        """Sets the rom_id of this GpuFlashedRom.

        Rom ID that was flashed  # noqa: E501

        :param rom_id: The rom_id of this GpuFlashedRom.  # noqa: E501
        :type: int
        """

        self._rom_id = rom_id

    @property
    def rom_name(self):
        """Gets the rom_name of this GpuFlashedRom.  # noqa: E501

        Rom name  # noqa: E501

        :return: The rom_name of this GpuFlashedRom.  # noqa: E501
        :rtype: str
        """
        return self._rom_name

    @rom_name.setter
    def rom_name(self, rom_name):
        """Sets the rom_name of this GpuFlashedRom.

        Rom name  # noqa: E501

        :param rom_name: The rom_name of this GpuFlashedRom.  # noqa: E501
        :type: str
        """

        self._rom_name = rom_name

    @property
    def time(self):
        """Gets the time of this GpuFlashedRom.  # noqa: E501

        When the ROM was flashed  # noqa: E501

        :return: The time of this GpuFlashedRom.  # noqa: E501
        :rtype: int
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this GpuFlashedRom.

        When the ROM was flashed  # noqa: E501

        :param time: The time of this GpuFlashedRom.  # noqa: E501
        :type: int
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GpuFlashedRom, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GpuFlashedRom):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GpuFlashedRom):
            return True

        return self.to_dict() != other.to_dict()
