# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class OCUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'options_update_mode': 'int'
    }

    attribute_map = {
        'options_update_mode': 'options_update_mode'
    }

    def __init__(self, options_update_mode=None, _configuration=None):  # noqa: E501
        """OCUpdateRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._options_update_mode = None
        self.discriminator = None

        if options_update_mode is not None:
            self.options_update_mode = options_update_mode

    @property
    def options_update_mode(self):
        """Gets the options_update_mode of this OCUpdateRequest.  # noqa: E501

        How options will be saved: * 1 - full update mode - options will be saved as a whole * 2 - partial update mode - only provided algos (or default) will be saved   # noqa: E501

        :return: The options_update_mode of this OCUpdateRequest.  # noqa: E501
        :rtype: int
        """
        return self._options_update_mode

    @options_update_mode.setter
    def options_update_mode(self, options_update_mode):
        """Sets the options_update_mode of this OCUpdateRequest.

        How options will be saved: * 1 - full update mode - options will be saved as a whole * 2 - partial update mode - only provided algos (or default) will be saved   # noqa: E501

        :param options_update_mode: The options_update_mode of this OCUpdateRequest.  # noqa: E501
        :type: int
        """

        self._options_update_mode = options_update_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OCUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OCUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OCUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
