# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PoolTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pool': 'str',
        'coin': 'CoinSymbol',
        'props': 'object'
    }

    attribute_map = {
        'pool': 'pool',
        'coin': 'coin',
        'props': 'props'
    }

    def __init__(self, pool=None, coin=None, props=None, _configuration=None):  # noqa: E501
        """PoolTemplate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._pool = None
        self._coin = None
        self._props = None
        self.discriminator = None

        if pool is not None:
            self.pool = pool
        if coin is not None:
            self.coin = coin
        if props is not None:
            self.props = props

    @property
    def pool(self):
        """Gets the pool of this PoolTemplate.  # noqa: E501

        Pool name  # noqa: E501

        :return: The pool of this PoolTemplate.  # noqa: E501
        :rtype: str
        """
        return self._pool

    @pool.setter
    def pool(self, pool):
        """Sets the pool of this PoolTemplate.

        Pool name  # noqa: E501

        :param pool: The pool of this PoolTemplate.  # noqa: E501
        :type: str
        """

        self._pool = pool

    @property
    def coin(self):
        """Gets the coin of this PoolTemplate.  # noqa: E501


        :return: The coin of this PoolTemplate.  # noqa: E501
        :rtype: CoinSymbol
        """
        return self._coin

    @coin.setter
    def coin(self, coin):
        """Sets the coin of this PoolTemplate.


        :param coin: The coin of this PoolTemplate.  # noqa: E501
        :type: CoinSymbol
        """

        self._coin = coin

    @property
    def props(self):
        """Gets the props of this PoolTemplate.  # noqa: E501


        :return: The props of this PoolTemplate.  # noqa: E501
        :rtype: object
        """
        return self._props

    @props.setter
    def props(self, props):
        """Sets the props of this PoolTemplate.


        :param props: The props of this PoolTemplate.  # noqa: E501
        :type: object
        """

        self._props = props

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoolTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoolTemplate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PoolTemplate):
            return True

        return self.to_dict() != other.to_dict()
