# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PowerDrawSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hardware_power_draw': 'int',
        'psu_efficiency': 'int',
        'octofan_correct_power': 'bool'
    }

    attribute_map = {
        'hardware_power_draw': 'hardware_power_draw',
        'psu_efficiency': 'psu_efficiency',
        'octofan_correct_power': 'octofan_correct_power'
    }

    def __init__(self, hardware_power_draw=None, psu_efficiency=None, octofan_correct_power=None, _configuration=None):  # noqa: E501
        """PowerDrawSettings - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hardware_power_draw = None
        self._psu_efficiency = None
        self._octofan_correct_power = None
        self.discriminator = None

        if hardware_power_draw is not None:
            self.hardware_power_draw = hardware_power_draw
        if psu_efficiency is not None:
            self.psu_efficiency = psu_efficiency
        if octofan_correct_power is not None:
            self.octofan_correct_power = octofan_correct_power

    @property
    def hardware_power_draw(self):
        """Gets the hardware_power_draw of this PowerDrawSettings.  # noqa: E501

        Power consumption of worker's hardware, watts  # noqa: E501

        :return: The hardware_power_draw of this PowerDrawSettings.  # noqa: E501
        :rtype: int
        """
        return self._hardware_power_draw

    @hardware_power_draw.setter
    def hardware_power_draw(self, hardware_power_draw):
        """Sets the hardware_power_draw of this PowerDrawSettings.

        Power consumption of worker's hardware, watts  # noqa: E501

        :param hardware_power_draw: The hardware_power_draw of this PowerDrawSettings.  # noqa: E501
        :type: int
        """

        self._hardware_power_draw = hardware_power_draw

    @property
    def psu_efficiency(self):
        """Gets the psu_efficiency of this PowerDrawSettings.  # noqa: E501

        Efficiency of power supply unit, %  # noqa: E501

        :return: The psu_efficiency of this PowerDrawSettings.  # noqa: E501
        :rtype: int
        """
        return self._psu_efficiency

    @psu_efficiency.setter
    def psu_efficiency(self, psu_efficiency):
        """Sets the psu_efficiency of this PowerDrawSettings.

        Efficiency of power supply unit, %  # noqa: E501

        :param psu_efficiency: The psu_efficiency of this PowerDrawSettings.  # noqa: E501
        :type: int
        """

        self._psu_efficiency = psu_efficiency

    @property
    def octofan_correct_power(self):
        """Gets the octofan_correct_power of this PowerDrawSettings.  # noqa: E501

        Apply power correction settings to power consumption value from Octominer fan controller. Default is false.  # noqa: E501

        :return: The octofan_correct_power of this PowerDrawSettings.  # noqa: E501
        :rtype: bool
        """
        return self._octofan_correct_power

    @octofan_correct_power.setter
    def octofan_correct_power(self, octofan_correct_power):
        """Sets the octofan_correct_power of this PowerDrawSettings.

        Apply power correction settings to power consumption value from Octominer fan controller. Default is false.  # noqa: E501

        :param octofan_correct_power: The octofan_correct_power of this PowerDrawSettings.  # noqa: E501
        :type: bool
        """

        self._octofan_correct_power = octofan_correct_power

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PowerDrawSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PowerDrawSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PowerDrawSettings):
            return True

        return self.to_dict() != other.to_dict()
