# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SignupRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'Password',
        'promocode': 'str',
        'ref_id': 'int'
    }

    attribute_map = {
        'password': 'password',
        'promocode': 'promocode',
        'ref_id': 'ref_id'
    }

    def __init__(self, password=None, promocode=None, ref_id=None, _configuration=None):  # noqa: E501
        """SignupRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._password = None
        self._promocode = None
        self._ref_id = None
        self.discriminator = None

        if password is not None:
            self.password = password
        if promocode is not None:
            self.promocode = promocode
        if ref_id is not None:
            self.ref_id = ref_id

    @property
    def password(self):
        """Gets the password of this SignupRequest.  # noqa: E501


        :return: The password of this SignupRequest.  # noqa: E501
        :rtype: Password
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this SignupRequest.


        :param password: The password of this SignupRequest.  # noqa: E501
        :type: Password
        """

        self._password = password

    @property
    def promocode(self):
        """Gets the promocode of this SignupRequest.  # noqa: E501

        Referral promocode  # noqa: E501

        :return: The promocode of this SignupRequest.  # noqa: E501
        :rtype: str
        """
        return self._promocode

    @promocode.setter
    def promocode(self, promocode):
        """Sets the promocode of this SignupRequest.

        Referral promocode  # noqa: E501

        :param promocode: The promocode of this SignupRequest.  # noqa: E501
        :type: str
        """

        self._promocode = promocode

    @property
    def ref_id(self):
        """Gets the ref_id of this SignupRequest.  # noqa: E501

        Referral ID  # noqa: E501

        :return: The ref_id of this SignupRequest.  # noqa: E501
        :rtype: int
        """
        return self._ref_id

    @ref_id.setter
    def ref_id(self, ref_id):
        """Sets the ref_id of this SignupRequest.

        Referral ID  # noqa: E501

        :param ref_id: The ref_id of this SignupRequest.  # noqa: E501
        :type: int
        """

        self._ref_id = ref_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SignupRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignupRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SignupRequest):
            return True

        return self.to_dict() != other.to_dict()
