# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TagIdsEdit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag_update_mode': 'str'
    }

    attribute_map = {
        'tag_update_mode': 'tag_update_mode'
    }

    def __init__(self, tag_update_mode='replace', _configuration=None):  # noqa: E501
        """TagIdsEdit - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._tag_update_mode = None
        self.discriminator = None

        if tag_update_mode is not None:
            self.tag_update_mode = tag_update_mode

    @property
    def tag_update_mode(self):
        """Gets the tag_update_mode of this TagIdsEdit.  # noqa: E501

        Update mode for tags * add - add spicified tags ignoring if already assigned; * remove - remove spicified tags if assigned; * replace - replace all assigned tags with specified ones;   # noqa: E501

        :return: The tag_update_mode of this TagIdsEdit.  # noqa: E501
        :rtype: str
        """
        return self._tag_update_mode

    @tag_update_mode.setter
    def tag_update_mode(self, tag_update_mode):
        """Sets the tag_update_mode of this TagIdsEdit.

        Update mode for tags * add - add spicified tags ignoring if already assigned; * remove - remove spicified tags if assigned; * replace - replace all assigned tags with specified ones;   # noqa: E501

        :param tag_update_mode: The tag_update_mode of this TagIdsEdit.  # noqa: E501
        :type: str
        """
        allowed_values = ["add", "remove", "replace"]  # noqa: E501
        if (self._configuration.client_side_validation and
                tag_update_mode not in allowed_values):
            raise ValueError(
                "Invalid value for `tag_update_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(tag_update_mode, allowed_values)
            )

        self._tag_update_mode = tag_update_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TagIdsEdit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TagIdsEdit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TagIdsEdit):
            return True

        return self.to_dict() != other.to_dict()
