# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WorkerOCAlgoResolved(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'oc_algo_resolved': 'str'
    }

    attribute_map = {
        'oc_algo_resolved': 'oc_algo_resolved'
    }

    def __init__(self, oc_algo_resolved=None, _configuration=None):  # noqa: E501
        """WorkerOCAlgoResolved - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._oc_algo_resolved = None
        self.discriminator = None

        if oc_algo_resolved is not None:
            self.oc_algo_resolved = oc_algo_resolved

    @property
    def oc_algo_resolved(self):
        """Gets the oc_algo_resolved of this WorkerOCAlgoResolved.  # noqa: E501

        Resolved overclock algorithm name based on applied flight sheet and tuning. This property just indicates which overclock should be applied. See \"oc_algo_actual\" for which is actually applied.   # noqa: E501

        :return: The oc_algo_resolved of this WorkerOCAlgoResolved.  # noqa: E501
        :rtype: str
        """
        return self._oc_algo_resolved

    @oc_algo_resolved.setter
    def oc_algo_resolved(self, oc_algo_resolved):
        """Sets the oc_algo_resolved of this WorkerOCAlgoResolved.

        Resolved overclock algorithm name based on applied flight sheet and tuning. This property just indicates which overclock should be applied. See \"oc_algo_actual\" for which is actually applied.   # noqa: E501

        :param oc_algo_resolved: The oc_algo_resolved of this WorkerOCAlgoResolved.  # noqa: E501
        :type: str
        """

        self._oc_algo_resolved = oc_algo_resolved

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkerOCAlgoResolved, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerOCAlgoResolved):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkerOCAlgoResolved):
            return True

        return self.to_dict() != other.to_dict()
