# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WorkerAsicConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asic_config': 'dict(str, str)'
    }

    attribute_map = {
        'asic_config': 'asic_config'
    }

    def __init__(self, asic_config=None, _configuration=None):  # noqa: E501
        """WorkerAsicConfig - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._asic_config = None
        self.discriminator = None

        if asic_config is not None:
            self.asic_config = asic_config

    @property
    def asic_config(self):
        """Gets the asic_config of this WorkerAsicConfig.  # noqa: E501

        Settings for ASICs with Hive firmware, depends on model and firmware version  # noqa: E501

        :return: The asic_config of this WorkerAsicConfig.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._asic_config

    @asic_config.setter
    def asic_config(self, asic_config):
        """Sets the asic_config of this WorkerAsicConfig.

        Settings for ASICs with Hive firmware, depends on model and firmware version  # noqa: E501

        :param asic_config: The asic_config of this WorkerAsicConfig.  # noqa: E501
        :type: dict(str, str)
        """

        self._asic_config = asic_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkerAsicConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerAsicConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkerAsicConfig):
            return True

        return self.to_dict() != other.to_dict()
