# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WorkerOCConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'oc_config': 'OCConfig',
        'oc_algo': 'OCAlgo'
    }

    attribute_map = {
        'oc_config': 'oc_config',
        'oc_algo': 'oc_algo'
    }

    def __init__(self, oc_config=None, oc_algo=None, _configuration=None):  # noqa: E501
        """WorkerOCConfig - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._oc_config = None
        self._oc_algo = None
        self.discriminator = None

        if oc_config is not None:
            self.oc_config = oc_config
        if oc_algo is not None:
            self.oc_algo = oc_algo

    @property
    def oc_config(self):
        """Gets the oc_config of this WorkerOCConfig.  # noqa: E501


        :return: The oc_config of this WorkerOCConfig.  # noqa: E501
        :rtype: OCConfig
        """
        return self._oc_config

    @oc_config.setter
    def oc_config(self, oc_config):
        """Sets the oc_config of this WorkerOCConfig.


        :param oc_config: The oc_config of this WorkerOCConfig.  # noqa: E501
        :type: OCConfig
        """

        self._oc_config = oc_config

    @property
    def oc_algo(self):
        """Gets the oc_algo of this WorkerOCConfig.  # noqa: E501


        :return: The oc_algo of this WorkerOCConfig.  # noqa: E501
        :rtype: OCAlgo
        """
        return self._oc_algo

    @oc_algo.setter
    def oc_algo(self, oc_algo):
        """Sets the oc_algo of this WorkerOCConfig.


        :param oc_algo: The oc_algo of this WorkerOCConfig.  # noqa: E501
        :type: OCAlgo
        """

        self._oc_algo = oc_algo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkerOCConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerOCConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkerOCConfig):
            return True

        return self.to_dict() != other.to_dict()
