# coding: utf-8

"""
    Hive OS API

    App API for Hive OS 2.0  # noqa: E501

    OpenAPI spec version: 2.1-beta
    Contact: brain@hiveos.farm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WorkerTunedMiners(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tuned_miners': 'list[MinerName]'
    }

    attribute_map = {
        'tuned_miners': 'tuned_miners'
    }

    def __init__(self, tuned_miners=None, _configuration=None):  # noqa: E501
        """WorkerTunedMiners - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._tuned_miners = None
        self.discriminator = None

        if tuned_miners is not None:
            self.tuned_miners = tuned_miners

    @property
    def tuned_miners(self):
        """Gets the tuned_miners of this WorkerTunedMiners.  # noqa: E501

        List of miner names from active flight sheet that are tuned in this worker.  # noqa: E501

        :return: The tuned_miners of this WorkerTunedMiners.  # noqa: E501
        :rtype: list[MinerName]
        """
        return self._tuned_miners

    @tuned_miners.setter
    def tuned_miners(self, tuned_miners):
        """Sets the tuned_miners of this WorkerTunedMiners.

        List of miner names from active flight sheet that are tuned in this worker.  # noqa: E501

        :param tuned_miners: The tuned_miners of this WorkerTunedMiners.  # noqa: E501
        :type: list[MinerName]
        """

        self._tuned_miners = tuned_miners

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkerTunedMiners, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerTunedMiners):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkerTunedMiners):
            return True

        return self.to_dict() != other.to_dict()
